# Generated by Django 5.1 on 2024-08-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyAppDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=4)),
                ('address', models.TextField(max_length=20)),
                ('phone', models.CharField(max_length=14)),
                ('registred_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
